#!/bin/sh
#
# Universal init script for start\stop anteater daemon
#

# Vars
SVCNAME="anteater"
EXEC="/opt/local/anteater/bin/anteater"
CONFIG_FILE="/etc/anteater/anteater.conf"
LOGS_DIR="/var/log/anteater"
PID_DIR="/var/run/anteater"
PID="$PID_DIR/anteater.pid"
USER="at"
GROUP="$USER"

# Create logs dir
install -o $USER -g $GROUP -d $LOGS_DIR $PID_DIR

do_start() {
	echo "Starting $SVCNAME"
	su - $USER -c "$EXEC -f $CONFIG_FILE >> $LOGS_DIR/info.log 2>> $LOGS_DIR/error.log &"
}

do_stop() {
	echo "Stopping $SVCNAME"
	pkill -2 -f $SVCNAME
}

case $1 in
	start|stop)
		do_$1
		;;
	restart)
		do_stop
		sleep 1
		do_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
